### PR TITLE
Prevent division by zero and add exports

### PR DESCRIPTION
**Pull request by heroin-moose**
The last commit contains a bunch of flaws. Sorry for that =/

### CODE REVIEW

**Comment by kazu-yamamoto** [comment]
Sorry but I don't understand why this "prevents division by zero". Would you explain?

**Comment by heroin-moose** [comment]
Gladly. Consider this kind of code:

```
$ cat test.hs
import Network.HTTP.Date
import Network.HTTP.Date.Converter

main :: IO ()
main = putStrLn $ show $ httpDateToUTC defaultHTTPDate

$ ./test
test: divide by zero
```

This happens because hour, minutes and seconds are zero.

**Comment by kazu-yamamoto** [comment]
The original code is `rem 24 (hdHour x)`.
The fixed one is `rem (hdHour x) 24`.
Does this mean that the original cod is buggy in addition to the possibility of zero division?

**Comment by heroin-moose** [comment]
Yes.

**Comment by kazu-yamamoto** [comment]
OK. I understand.

So, I would like ask you to add doctest for `httpDateToUTC` and `utcToHTTPDate`.

**Comment by heroin-moose** [comment]
True enough, I should've done it in the first place.

**Comment by kazu-yamamoto** [comment]
Ping @heroin-moose

**Comment by heroin-moose** [comment]
Sorry, got distracted by another things. I'll send you the tests by the end of the week, okay?

**Comment by kazu-yamamoto** [comment]
Yes. It's up to you!

**Comment by heroin-moose** [comment]
Okay, now we have the tests.

**Comment by kazu-yamamoto** [comment]
Thank you for your contribution! A new version has been released.

**Pull request merged**
